import { mutation, query } from './_generated/server'
import { v } from 'convex/values'

const productLink=v.object({category:v.string(),name:v.string(),url:v.string()})
const institution=v.object({id:v.string(),nameKm:v.string(),nameEn:v.string(),short:v.string(),typeKm:v.string(),typeEn:v.string(),verified:v.boolean(),deposits:v.boolean(),rating:v.number(),reviews:v.number(),provinces:v.array(v.string()),descriptionKm:v.string(),descriptionEn:v.string(),services:v.array(v.string()),color:v.string(),logo:v.optional(v.union(v.string(),v.null())),cmaMember:v.boolean(),sourceUrl:v.string(),checkedAt:v.string(),sourceName:v.union(v.literal('CMA'),v.literal('NBC')),website:v.optional(v.string()),email:v.optional(v.string()),hotline:v.optional(v.string()),address:v.optional(v.string()),officialDescription:v.optional(v.string()),officialCheckedAt:v.optional(v.string()),websiteResearchStatus:v.optional(v.union(v.literal('fetched'),v.literal('partial'),v.literal('unreachable'),v.literal('no_website'))),officialEmails:v.optional(v.array(v.string())),officialPhones:v.optional(v.array(v.string())),socialLinks:v.optional(v.array(v.string())),appLinks:v.optional(v.array(v.string())),productLinks:v.optional(v.array(productLink)),evidenceUrls:v.optional(v.array(v.string())),pagesChecked:v.optional(v.number()),csxListed:v.boolean(),csxSecurityType:v.optional(v.union(v.literal('equity'),v.literal('bond'),v.literal('equity_and_bond'))),csxSymbol:v.optional(v.string()),csxSourceUrl:v.string(),csxCheckedAt:v.string()})
const term=v.object({slug:v.string(),km:v.string(),en:v.string(),defKm:v.string(),defEn:v.string()})
export const batch=mutation({args:{institutions:v.array(institution),glossary:v.array(term)},handler:async(ctx,args)=>{for(const{id:slug,...value}of args.institutions){const existing=await ctx.db.query('institutions').withIndex('by_slug',q=>q.eq('slug',slug)).unique();const record={...value,slug,published:true,updatedAt:Date.now()};if(existing)await ctx.db.patch(existing._id,record);else await ctx.db.insert('institutions',record)}for(const value of args.glossary){const existing=await ctx.db.query('glossaryTerms').withIndex('by_slug',q=>q.eq('slug',value.slug)).unique();const record={...value,status:'published' as const,updatedAt:Date.now()};if(existing)await ctx.db.patch(existing._id,record);else await ctx.db.insert('glossaryTerms',record)}return{institutions:args.institutions.length,glossary:args.glossary.length}}})

export const stats=query({args:{},handler:async ctx=>({institutions:(await ctx.db.query('institutions').collect()).length,glossaryTerms:(await ctx.db.query('glossaryTerms').collect()).length,sources:(await ctx.db.query('sources').collect()).length,verificationRecords:(await ctx.db.query('verificationRecords').collect()).length,reviews:(await ctx.db.query('reviews').collect()).length})})
