import { ArrowLeft, BadgeCheck, BarChart3, CalendarDays, Check, CircleHelp, ExternalLink, Globe2, Heart, Info, Landmark, Mail, MapPin, Phone, ShieldCheck } from 'lucide-react'
import type { Institution } from './types'

type Locale = 'km' | 'en'
type Props = { institution:Institution; locale:Locale; t:{notVerified:string;reviews:string}; go:(path:string)=>void }

function Logo({institution}: {institution:Institution}) {
  return <span className="institution-logo large" style={{background:institution.logo?'#fff':institution.color}}>{institution.logo?<img src={institution.logo} alt=""/>:institution.short}</span>
}

export function InstitutionPage({institution:i,locale,t,go}:Props) {
  const km=locale==='km'
  const nbcVerified=i.verified&&i.sourceName==='NBC'
  const metrics = [
    {label:km?'ការផ្ទៀងផ្ទាត់និយតករ':'Regulatory verification',value:nbcVerified?100:35,note:nbcVerified?(km?'បានផ្គូផ្គងនឹងបញ្ជី NBC':'Matched to the NBC list'):(km?'មិនទាន់ផ្គូផ្គងនឹង NBC':'NBC match not completed')},
    {label:km?'ភាពពេញលេញនៃទិន្នន័យ':'Data completeness',value:Math.round(([i.website,i.hotline||i.officialPhones?.[0],i.email||i.officialEmails?.[0],i.address,i.services.length].filter(Boolean).length/5)*100),note:km?'ផ្អែកលើទំនាក់ទំនង និងព័ត៌មានសេវាផ្លូវការ':'Based on official contact and service information'},
    {label:km?'ការគ្របដណ្តប់ប្រភពផ្លូវការ':'Official-source coverage',value:Math.min(100,(i.pagesChecked??0)*20),note:km?`${i.pagesChecked??0} ទំព័រត្រូវបានពិនិត្យ`:`${i.pagesChecked??0} pages checked`},
  ]
  return <div className="institution-page page">
    <button className="back" onClick={()=>go('/institutions')}><ArrowLeft/>{km?'ត្រឡប់ទៅលទ្ធផល':'Back to results'}</button>
    <section className="institution-summary"><Logo institution={i}/><div className="institution-heading"><span className={`badge ${nbcVerified?'ok':'neutral'}`}>{nbcVerified?<BadgeCheck/>:<CircleHelp/>}{nbcVerified?(km?'បានផ្ទៀងផ្ទាត់តាម NBC':'NBC verified'):(km?'មានក្នុងបញ្ជី CMA':'Listed by CMA')}</span><h1>{i.nameEn}</h1><p>{km?i.typeKm:i.typeEn}</p><span className={`csx-summary ${i.csxListed?'listed':'not-listed'}`}><Landmark/>{i.csxListed?(km?`មានមូលបត្រចុះបញ្ជីនៅ ផមក · ${i.csxSymbol}`:`CSX listed · ${i.csxSymbol}`):(km?'មិនមានមូលបត្រក្នុងបញ្ជី ផមក បច្ចុប្បន្ន':'No current CSX listing')}</span></div><div className="institution-actions">{i.website&&<a className="website-button" href={i.website} target="_blank" rel="noreferrer"><Globe2/>{km?'គេហទំព័រ':'Website'}<ExternalLink/></a>}<button className="save-button"><Heart/>{km?'រក្សាទុក':'Save'}</button></div></section>
    <div className="institution-layout"><div className="institution-main"><section className="panel details-panel"><h2>{km?'ព័ត៌មានសំខាន់ៗ':'Key details'}</h2>{i.officialDescription&&<p className="official-description">{i.officialDescription}</p>}<dl className="institution-facts"><div><dt>{km?'ប្រភេទ':'Institution type'}</dt><dd>{km?i.typeKm:i.typeEn}</dd></div><div><dt>{km?'ទទួលប្រាក់បញ្ញើ':'Accepts deposits'}</dt><dd>{i.deposits?(km?'បាទ/ចាស':'Yes'):(km?'ទេ':'No')}</dd></div></dl>
        {(i.hotline||i.email||i.address||i.officialPhones?.length||i.officialEmails?.length)&&<div className="official-contact"><h3>{km?'ទំនាក់ទំនងផ្លូវការ':'Official contact'}</h3>{(i.hotline||i.officialPhones?.[0])&&<p><Phone/>{i.hotline||i.officialPhones?.[0]}</p>}{(i.email||i.officialEmails?.[0])&&<p><Mail/>{i.email||i.officialEmails?.[0]}</p>}{i.address&&<p><MapPin/>{i.address}</p>}</div>}
      </section>
      <section className="panel products-panel"><div className="products-heading"><div><h2>{km?'សេវា និងផលិតផល':'Services and products'}</h2><p>{km?'បានរកឃើញលើគេហទំព័រផ្លូវការរបស់គ្រឹះស្ថាន។':'Found on the institution’s official website.'}</p></div>{i.officialCheckedAt&&<small><CalendarDays/>{i.officialCheckedAt}</small>}</div>{i.services.length?<div className="service-tags">{i.services.map(service=><span key={service}>{service}</span>)}</div>:<p className="empty-products">{km?'គេហទំព័រមិនបានបង្ហាញព័ត៌មានដែលអាចយកបាន។':'No extractable product information was published.'}</p>}{i.productLinks?.length?<div className="product-link-grid">{i.productLinks.slice(0,18).map(product=><a key={`${product.category}-${product.url}`} href={product.url} target="_blank" rel="noreferrer"><small>{product.category}</small><span>{product.name||product.category}</span><ExternalLink/></a>)}</div>:null}</section>
      <section className="panel performance-section"><div className="performance-heading"><BarChart3/><div><h2>{km?'ការវាយតម្លៃរបស់ Finឆែក':'FinCheck assessment'}</h2><p>{km?'រង្វាស់ទាំងនេះគណនាដោយ Finឆែក ពីប្រភពផ្លូវការ មិនមែនជាមតិអ្នកប្រើប្រាស់ទេ។':'These metrics are calculated by FinCheck from official sources—not user reviews.'}</p></div></div><div className="metric-list">{metrics.map(metric=><article key={metric.label}><div><b>{metric.label}</b><strong>{metric.value}%</strong></div><span className="metric-track"><i style={{width:`${metric.value}%`}}/></span><small>{metric.note}</small></article>)}</div><p className="assessment-note"><Info/>{km?'ពិន្ទុនេះបង្ហាញគុណភាព និងភាពពេញលេញនៃព័ត៌មានដែលយើងបានស្រាវជ្រាវ មិនមែនគុណភាពសេវាកម្ម ឬអនុសាសន៍វិនិយោគទេ។':'This score describes the quality and completeness of our research, not service quality or an investment recommendation.'}</p></section></div>
      <aside className="institution-aside"><section className="panel source-panel"><div className="source-heading"><ShieldCheck/><div><h3>{km?'ការផ្ទៀងផ្ទាត់':'Verification'}</h3><p>{nbcVerified?(km?'មានក្នុងបញ្ជីផ្លូវការ NBC':'Matched to the official NBC list'):t.notVerified}</p></div></div>{!nbcVerified&&<p className="verification-note">{km?'អាជ្ញាបណ្ណ NBC មិនទាន់ត្រូវបានផ្ទៀងផ្ទាត់។':'NBC licence not yet verified.'}</p>}<a className="source-link" href={i.sourceUrl} target="_blank" rel="noreferrer">{i.sourceName} {km?'ប្រភពបញ្ជី':'directory source'}<ExternalLink/></a>{i.evidenceUrls?.length?<div className="website-evidence"><b>{km?'ទំព័រផ្លូវការដែលបានពិនិត្យ':'Official pages checked'}</b><span>{i.pagesChecked} {km?'ទំព័រ':'pages'}</span>{i.evidenceUrls.slice(0,5).map((url,index)=><a href={url} target="_blank" rel="noreferrer" key={url}>{index===0?(km?'គេហទំព័រចម្បង':'Main website'):`${km?'ប្រភព':'Source'} ${index+1}`}<ExternalLink/></a>)}</div>:null}</section><section className="panel csx-card"><Landmark/><div><b>{km?'ផ្សារមូលបត្រកម្ពុជា (ផមក)':'Cambodia Securities Exchange (CSX)'}</b><p>{i.csxListed?(km?`បានផ្ទៀងផ្ទាត់មូលបត្រ ${i.csxSymbol} ក្នុងបញ្ជីបច្ចុប្បន្ន។`:`${i.csxSymbol} appears in the current securities list.`):(km?'មិនបានរកឃើញមូលបត្ររបស់គ្រឹះស្ថាននេះក្នុងបញ្ជីបច្ចុប្បន្ន។':'No current securities listing found for this institution.')}</p><a className="source-link" href={i.csxSourceUrl} target="_blank" rel="noreferrer">{km?'ពិនិត្យប្រភព ផមក':'View CSX source'}<ExternalLink/></a><small>{km?'ពិនិត្យថ្ងៃទី':'Checked'} {i.csxCheckedAt}</small></div></section></aside>
    </div>
  </div>
}
