import { useState, type FormEvent } from 'react'
import { useMutation, useQuery } from 'convex/react'
import { makeFunctionReference } from 'convex/server'
import { ArrowLeft, BadgeCheck, CalendarDays, CircleHelp, ExternalLink, Globe2, Heart, Info, Mail, MapPin, MessageSquareText, Phone, ShieldCheck, Star, UserRound, X } from 'lucide-react'
import type { Institution } from './types'

type Locale = 'km' | 'en'
type Review = { overall:number; transparency:number; treatment:number; service:number; title:string; body:string; firsthand:boolean; date:string }
type Props = { institution:Institution; locale:Locale; t:{notVerified:string;reviews:string}; go:(path:string)=>void }

function Logo({institution}: {institution:Institution}) {
  return <span className="institution-logo large" style={{background:institution.logo?'#fff':institution.color}}>{institution.logo?<img src={institution.logo} alt=""/>:institution.short}</span>
}

function Stars({value,onChange}:{value:number;onChange?:(value:number)=>void}) {
  return <div className="star-rating" aria-label={`${value} out of 5`}>{[1,2,3,4,5].map(n=><button type="button" key={n} disabled={!onChange} className={n<=value?'filled':''} onClick={()=>onChange?.(n)} aria-label={`${n} stars`}><Star fill="currentColor"/></button>)}</div>
}

export function InstitutionPage({institution:i,locale,t,go}:Props) {
  const [visitorId]=useState(()=>{const key='pisey-visitor-id';const current=localStorage.getItem(key);if(current)return current;const value=crypto.randomUUID();localStorage.setItem(key,value);return value})
  const review=useQuery(makeFunctionReference<'query',{institutionSlug:string;visitorId:string},Review|null>('reviews:mine'),{institutionSlug:i.id,visitorId})
  const upsertReview=useMutation(makeFunctionReference<'mutation',Review&{institutionSlug:string;visitorId:string},unknown>('reviews:upsertMine'))
  const [open,setOpen]=useState(false)
  const km=locale==='km'
  const nbcVerified=i.verified&&i.sourceName==='NBC'
  return <div className="institution-page page">
    <button className="back" onClick={()=>go('/institutions')}><ArrowLeft/>{km?'ត្រឡប់ទៅលទ្ធផល':'Back to results'}</button>
    <section className="institution-summary"><Logo institution={i}/><div className="institution-heading"><span className={`badge ${nbcVerified?'ok':'neutral'}`}>{nbcVerified?<BadgeCheck/>:<CircleHelp/>}{nbcVerified?(km?'បានផ្ទៀងផ្ទាត់តាម NBC':'NBC verified'):(km?'មានក្នុងបញ្ជី CMA':'Listed by CMA')}</span><h1>{i.nameEn}</h1><p>{km?i.typeKm:i.typeEn}</p><span className="review-count"><MessageSquareText/>{review?(km?'មតិរបស់អ្នកបានរក្សាទុក':'Your review is saved'):(km?'មិនទាន់មានមតិ':'No community reviews yet')}</span></div><div className="institution-actions">{i.website&&<a className="website-button" href={i.website} target="_blank" rel="noreferrer"><Globe2/>{km?'គេហទំព័រ':'Website'}<ExternalLink/></a>}<button className="save-button"><Heart/>{km?'រក្សាទុក':'Save'}</button></div></section>
    <div className="institution-layout"><div className="institution-main"><section className="panel details-panel"><h2>{km?'ព័ត៌មានសំខាន់ៗ':'Key details'}</h2>{i.officialDescription&&<p className="official-description">{i.officialDescription}</p>}<dl className="institution-facts"><div><dt>{km?'ប្រភេទ':'Institution type'}</dt><dd>{km?i.typeKm:i.typeEn}</dd></div><div><dt>{km?'ទទួលប្រាក់បញ្ញើ':'Accepts deposits'}</dt><dd>{i.deposits?(km?'បាទ/ចាស':'Yes'):(km?'ទេ':'No')}</dd></div></dl>
        {(i.hotline||i.email||i.address||i.officialPhones?.length||i.officialEmails?.length)&&<div className="official-contact"><h3>{km?'ទំនាក់ទំនងផ្លូវការ':'Official contact'}</h3>{(i.hotline||i.officialPhones?.[0])&&<p><Phone/>{i.hotline||i.officialPhones?.[0]}</p>}{(i.email||i.officialEmails?.[0])&&<p><Mail/>{i.email||i.officialEmails?.[0]}</p>}{i.address&&<p><MapPin/>{i.address}</p>}</div>}
      </section>
      <section className="panel products-panel"><div className="products-heading"><div><h2>{km?'សេវា និងផលិតផល':'Services and products'}</h2><p>{km?'បានរកឃើញលើគេហទំព័រផ្លូវការរបស់គ្រឹះស្ថាន។':'Found on the institution’s official website.'}</p></div>{i.officialCheckedAt&&<small><CalendarDays/>{i.officialCheckedAt}</small>}</div>{i.services.length?<div className="service-tags">{i.services.map(service=><span key={service}>{service}</span>)}</div>:<p className="empty-products">{km?'គេហទំព័រមិនបានបង្ហាញព័ត៌មានដែលអាចយកបាន។':'No extractable product information was published.'}</p>}{i.productLinks?.length?<div className="product-link-grid">{i.productLinks.slice(0,18).map(product=><a key={`${product.category}-${product.url}`} href={product.url} target="_blank" rel="noreferrer"><small>{product.category}</small><span>{product.name||product.category}</span><ExternalLink/></a>)}</div>:null}</section>
      <section className="panel reviews-section"><div className="reviews-heading"><div><h2>{t.reviews}</h2><p>{km?'ចែករំលែកព័ត៌មានដែលមានប្រយោជន៍ ដោយរក្សាឯកជនភាព។':'Share something useful while protecting your privacy.'}</p></div><button className="primary" onClick={()=>setOpen(true)}>{review?(km?'កែមតិ':'Edit review'):(km?'សរសេរមតិ':'Write a review')}</button></div>{review?<article className="saved-review"><div className="saved-review-head"><span className="avatar"><UserRound/></span><div><b>{km?'មតិរបស់អ្នក':'Your review'}</b><Stars value={review.overall}/><small>{new Date(review.date).toLocaleDateString()}</small></div></div>{review.title&&<h3>{review.title}</h3>}<p>{review.body}</p><div className="rating-breakdown"><span>{km?'ថ្លៃសេវាច្បាស់លាស់':'Fee transparency'} <b>{review.transparency}/5</b></span><span>{km?'ការគោរពពីបុគ្គលិក':'Staff treatment'} <b>{review.treatment}/5</b></span><span>{km?'បទពិសោធន៍សេវា':'Service experience'} <b>{review.service}/5</b></span></div></article>:<div className="review-empty"><MessageSquareText/><h3>{km?'មិនទាន់មានមតិ':'No reviews yet'}</h3><p>{km?'ក្លាយជាអ្នកដំបូងដែលចែករំលែកបទពិសោធន៍ផ្ទាល់។':'Be the first to share a firsthand experience.'}</p></div>}</section></div>
      <aside className="institution-aside"><section className="panel source-panel"><div className="source-heading"><ShieldCheck/><div><h3>{km?'ការផ្ទៀងផ្ទាត់':'Verification'}</h3><p>{nbcVerified?(km?'មានក្នុងបញ្ជីផ្លូវការ NBC':'Matched to the official NBC list'):t.notVerified}</p></div></div>{!nbcVerified&&<p className="verification-note">{km?'អាជ្ញាបណ្ណ NBC មិនទាន់ត្រូវបានផ្ទៀងផ្ទាត់។':'NBC licence not yet verified.'}</p>}<a className="source-link" href={i.sourceUrl} target="_blank" rel="noreferrer">{i.sourceName} {km?'ប្រភពបញ្ជី':'directory source'}<ExternalLink/></a>{i.evidenceUrls?.length?<div className="website-evidence"><b>{km?'ទំព័រផ្លូវការដែលបានពិនិត្យ':'Official pages checked'}</b><span>{i.pagesChecked} {km?'ទំព័រ':'pages'}</span>{i.evidenceUrls.slice(0,5).map((url,index)=><a href={url} target="_blank" rel="noreferrer" key={url}>{index===0?(km?'គេហទំព័រចម្បង':'Main website'):`${km?'ប្រភព':'Source'} ${index+1}`}<ExternalLink/></a>)}</div>:null}</section><section className="panel privacy-card"><Info/><div><b>{km?'ការពារឯកជនភាព':'Protect your privacy'}</b><p>{km?'កុំចែករំលែកលេខគណនី អត្តសញ្ញាណប័ណ្ណ លេខទូរស័ព្ទ ឬឈ្មោះបុគ្គលិក។':'Do not share account numbers, IDs, phone numbers, or staff names.'}</p></div></section></aside>
    </div>{open&&<ReviewDialog locale={locale} initial={review??null} close={()=>setOpen(false)} save={async value=>{await upsertReview({...value,institutionSlug:i.id,visitorId});setOpen(false)}}/>}
  </div>
}

function ReviewDialog({locale,initial,close,save}:{locale:Locale;initial:Review|null;close:()=>void;save:(review:Review)=>void|Promise<void>}) {
  const km=locale==='km'; const [form,setForm]=useState<Review>(initial??{overall:0,transparency:0,treatment:0,service:0,title:'',body:'',firsthand:false,date:new Date().toISOString()}); const [error,setError]=useState('')
  const rate=(field:'overall'|'transparency'|'treatment'|'service',label:string)=><div className="rating-field"><span>{label}</span><Stars value={form[field]} onChange={value=>setForm({...form,[field]:value})}/></div>
  const submit=(e:FormEvent)=>{e.preventDefault();if(!form.overall||!form.transparency||!form.treatment||!form.service)return setError(km?'សូមវាយតម្លៃគ្រប់ផ្នែក។':'Please rate every category.');if(form.body.trim().length<40)return setError(km?'សូមសរសេរយ៉ាងតិច ៤០ តួអក្សរ។':'Please write at least 40 characters.');if(!form.firsthand)return setError(km?'សូមបញ្ជាក់ថានេះជាបទពិសោធន៍ផ្ទាល់។':'Confirm this is a firsthand experience.');save({...form,title:form.title.trim(),body:form.body.trim()})}
  return <div className="dialog-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><section className="review-dialog" role="dialog" aria-modal="true" aria-labelledby="review-dialog-title"><header><div><span>{km?'មតិសហគមន៍':'Community review'}</span><h2 id="review-dialog-title">{initial?(km?'កែមតិរបស់អ្នក':'Edit your review'):(km?'ចែករំលែកបទពិសោធន៍':'Share your experience')}</h2></div><button onClick={close} aria-label="Close"><X/></button></header><div className="review-warning"><ShieldCheck/><p>{km?'កុំបញ្ចូលលេខគណនី លេខអត្តសញ្ញាណ លេខទូរស័ព្ទ ចំនួនបំណុលពិតប្រាកដ ឬឈ្មោះបុគ្គលិក។':'Do not include account or ID numbers, phone numbers, exact debt balances, or staff names.'}</p></div><form onSubmit={submit}>{rate('overall',km?'ការវាយតម្លៃសរុប':'Overall experience')}{rate('transparency',km?'ភាពច្បាស់លាស់នៃថ្លៃសេវា':'Fee transparency')}{rate('treatment',km?'ការគោរពពីបុគ្គលិក':'Staff treatment')}{rate('service',km?'ដំណើរការ និងសេវា':'Process and service')}<label className="review-input"><span>{km?'ចំណងជើង (មិនបាច់)':'Title (optional)'}</span><input maxLength={80} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="review-input"><span>{km?'បទពិសោធន៍របស់អ្នក':'Your experience'}</span><textarea maxLength={1200} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder={km?'អ្វីដែលមានប្រយោជន៍សម្រាប់អ្នកដទៃដឹង?':'What would be useful for others to know?'}/><small>{form.body.length}/1200</small></label><label className="confirmation"><input type="checkbox" checked={form.firsthand} onChange={e=>setForm({...form,firsthand:e.target.checked})}/><span>{km?'ខ្ញុំបញ្ជាក់ថានេះជាបទពិសោធន៍ផ្ទាល់របស់ខ្ញុំ។':'I confirm this is my firsthand experience.'}</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<footer><button type="button" className="secondary" onClick={close}>{km?'បោះបង់':'Cancel'}</button><button className="primary">{km?'រក្សាទុកមតិ':'Save review'}</button></footer></form></section></div>
}
